services:
  - type: web
    name: exoplanet-transit-classifier
    env: python
    plan: free
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt --extra-index-url https://download.pytorch.org/whl/cpu
    startCommand: gunicorn -c gunicorn.conf.py dashboard:server